name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --windowed --name LyricSyncPro main.py

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: LyricSyncPro-windows
          path: dist/LyricSyncPro/**

  release:
    needs: build-windows
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: LyricSyncPro-windows
          path: dist

      - name: Zip
        run: |
          cd dist
          zip -r "LyricSyncPro-windows-${{ github.ref_name }}-autobuild.zip" .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ github.ref_name }} [autobuild]"
          body: |
            This is an autobuild generated by GitHub Actions.
            - Workflow: ${{ github.workflow }}
            - Run ID: ${{ github.run_id }}
            - Commit: ${{ github.sha }}
          files: dist/LyricSyncPro-windows-${{ github.ref_name }}-autobuild.zip
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
